### ISSUE TITLE
Is there a way to use different tasks to build test.

### ISSUE THREAD

**Issue by mvitiuk** [browserstack/browserstack-gradle-plugin#10]
Hello, it's a very useful plugin, but we have different (a lot) variants to build and so different debug tasks, I don't want to run all of them, but rather some. Is there a way to change `assembleDebugAndroidTest` to something else?

Like use `assembleMyVariantDebugAndroidTest` ?

Thank you in advance.

**Comment by kalamcs** [comment]
Hey, this is a good suggestion - and we will definitely pick it up. Have added it to our roadmap. But, in the interim, if it is a burning issue - you can even raise a PR.

**Comment by kalamcs** [comment]
Hi @mvitiuk 

We have released an update to this plugin - which will allow building/testing against different variants. Please try it out - and keep sharing your suggestions/inputs.

**Comment by mvitiuk** [comment]
Hi @kalamcs Plugin works well, I'm able to push my test successfully to browserstack. The only thing is I'm getting "BUILD SUCCESSFUL" when tests are just pushed to BS. 

Is it possible to get response with fail/not fail after the tests are done like for selenium?
That would be very nice, since we want to know is it safe to merge for pull requests when tests are run in Travis.

**Comment by kalamcs** [comment]
Oh, that can easily be achieved by setting the callbackURL in your configuration. We will hit that url when the build execution is complete (Refer https://www.browserstack.com/app-automate/espresso/get-started).

We support the callbackURL in the configuration of the gradle plugin as well.

**Comment by kalamcs** [comment]
Closing the issue.
