### ISSUE TITLE
gradle plugin for web testing ?

### ISSUE THREAD

**Issue by mmanach** [browserstack/browserstack-gradle-plugin#11]
Hello, 

I saw in the readme that this plugin seems to be oriented to Espresso, but is it possible to run classical web tests with browsers ?

Thanks,

**Comment by kalamcs** [comment]
Can you please elaborate your use-case for us to understand better.

Thanks and regards
Kalam

**Comment by mmanach** [comment]
I mean : I use gradle, so if I want to run my web tests (with firefox, chrome, safari, IE... on different OS) with browserstack, should I use this **browserstack-gradle-plugin** ? Or it is only dedicated to Mobile / Espresso testing ? 

Thanks

**Comment by mmanach** [comment]
We are using Serenity (https://github.com/serenity-bdd/serenity-core), based on JUnit (with JBehave).
I saw on your example https://www.browserstack.com/automate/serenity, and custom Driver is implemented, with different profiles with Maven.

We success to run with gradle just by adding some arguments : 

- -Dbrowserstack.local=
- -Dbrowserstack.url=http://{USER}:{KEY}@hub.browserstack.com:80/wd/hub
- -Dbrowserstack.browser=
- -Dbrowserstack.browser_version=
- -Dbrowserstack.os=
- -Dbrowserstack.os_version=
- -Dbrowserstack.build=

**Comment by kalamcs** [comment]
Happy to know that it worked for you. :)
