### ISSUE TITLE
Add project parameters to EspressoTask

### ISSUE THREAD

**Issue by badoualy** [browserstack/browserstack-gradle-plugin#23]
The plugin is missing the "project" parameters to group builds under one project.
Would be nice to have it

> project (optional): Set this parameter if you would like to group your test executions under one build. Example: \"project\": \"project123\"

Thanks

**Comment by anthony-fdes** [comment]
Hi, thanks for the feedback. We have communicated this to our product team and we shall update you once the plugin is updated.

**Comment by agundawar** [comment]
This is supported now. Parameters can be sent with the help of configuration file. Closing this.
