### ISSUE TITLE
Field configFIlePath is mandatory

### ISSUE THREAD

**Issue by VladSVAssets** [browserstack/browserstack-gradle-plugin#29]
Hello,

Running the task uploadReleaseToBrowserstackAppLive, returns this error on Gitlab :

 > Task :app:uploadReleaseToBrowserstackAppLive FAILED
 > Task :app:packageReleaseBundle
 FAILURE: Build failed with an exception.
 * What went wrong:
 A problem was found with the configuration of task ':app:uploadReleaseToBrowserstackAppLive'.
 47 actionable tasks: 47 executed
 > No value has been specified for property 'configFilePath'.

I had the username and accessKey set in environment variables with names BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY as specified in the documentation. But I receive the error above.  

On the documentation is specified that "Note: username, accessKey and devices are mandatory parameters." but does not say that the configFilePath is mandatory, or how it can be disabled. For my case, I do not need the Espresso tests to be ran automatically, so I do not want to set the configFilePath.

So can you make me understand what should I do in order to use this version with tests disabled?

Thank you!

**Comment by dharmendrajha** [comment]
@VladSVAssets A fix has been deployed for this issue.

**Comment by VladSVAssets** [comment]
Thank you! I will test and leave a message here with the result. Much appreciated! @dharmendrajha

**Comment by VladSVAssets** [comment]
Hello! I tested the version 3.0.1, and I can confirm that the build upload automation works without the 'configFilePath'. Thank you!
