### ISSUE TITLE
Support defining a custom_id to upload task

### ISSUE THREAD

**Issue by gekylafas** [browserstack/browserstack-gradle-plugin#36]
[Uploading an APK with curl](https://www.browserstack.com/app-live/rest-api) allows you to define a `custom_id` for the app. However, the plugin does not seem to support this feature.
Could you please add it?

**Comment by dharmendrajha** [comment]
Hey @gekylafas, adding support for custom_id with the Gradle plugin not on our current roadmap. However, we have made a note of this request.

**Comment by marius-m** [comment]
Not sure if this'll be merged in, but I needed that as well, so created a pull request with this feature - https://github.com/browserstack/browserstack-gradle-plugin/pull/43

**Comment by deepwired** [comment]
You changes have been tested and merged

We have also fixed the unit tests and bumped our gradle version to 3.0.4, this is currently published, PFB
https://plugins.gradle.org/plugin/com.browserstack.gradle

Will update the Readme with how to contribute steps to make future open source contributions a little easier.


Special thanks to @marius-m and @Sankalan1987 for their contributions :) 

Closing this thread for now.
