### ISSUE TITLE
Gradle 7.0 - Missing annotation

### ISSUE THREAD

**Issue by sagix** [browserstack/browserstack-gradle-plugin#38]
Hi, 

When I try to run espresso tests with the browserstack plugin and *gradle 7.0*.

I get this error :  

```
* What went wrong:
A problem was found with the configuration of task ':app:executeMeeticExternalDebugTestsOnBrowserstack' (type 'EspressoTask').
  - Type 'EspressoTask' property 'host' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

In the base task : BrowserStackTask

`@Input` annotation should be added and a getter to AppVariantBaseName

```java
    @Input
    private String host;

    @Input
    private String appVariantBaseName = "debug";

    public String getAppVariantBaseName() {
        return appVariantBaseName;
    }
```

**Comment by browserstack-support** [comment]
Hi,     Thank you for your patience.  ​   I would like to let you know that we have released a new version of browserstack-gradle-plugin , 3.0.3. This version is compatible with Gradle 7.  ​   Can you kindly give the above a try and let us know of any queries and we will be happy to help.   ​     Regards,  Harsh Pathar  BrowserStack Support      
                           
                            On
                            Mon, 26 Apr at  1:12 PM
                            ,  browserstack/browserstack-gradle-plugin ***@***.***>  wrote:
                             
 Hi, 
 When I try to run espresso tests with the browserstack plugin and gradle 7.0. 
 I get this error : 
 * What went wrong:
A problem was found with the configuration of task ':app:executeMeeticExternalDebugTestsOnBrowserstack' (type 'EspressoTask').
  - Type 'EspressoTask' property 'host' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to http://email.browserstack.com/c/eJwdT8mOwyAU-5rkFpQQCOWQw8xhfqNieSwdlgRIq_79MJWsJ-vZlmy9U0k1G_2-zRwLzcWN8ZneF9iwkGzZOlGrIuuydglVr-HXn5MpcF6Q2mT0dGR9VRC1LVMUPq2TDBdM7EYUN8ZIOT1OwuVAZuhyQD1anYb6i1SOo9sVmxdBOGyMU2qAbxtZuaKcaG6wxGoMu2vtqMP6NeCfDp1VRbYIHQDlYvuHobnfXqLYqxfs_CmC16L5nO5HyTJArMi1GAa8Rl-rT_YuUsrtYxnLXuAI7wF_iyhtov40_vUyzFrMMmWWbvXh2AOeMjmnXXzTA_qeTwhZ39wl_8f8ARbzbus for more details about this problem.
 
 In the base task : BrowserStackTask 
 
@Input annotation should be added and a getter to AppVariantBaseName 
      @Input
    private String host;

    @Input
    private String appVariantBaseName = "debug";

    public String getAppVariantBaseName() {
        return appVariantBaseName;
    }

**Comment by wuyuansu** [comment]
but if BrowserStackTask is 'File is read-only‘ ,because it is in a jar file.how can to add anotation?
