### ISSUE TITLE
Set custom_id for `uploadDebugToBrowserstackAppLive`

### ISSUE THREAD

**Issue by saxophone** [browserstack/browserstack-gradle-plugin#49]
Hi, I have set up a GitHub action to upload my app to BrowserStack App Live every night. This means that over the course of 30 days (the auto-delete threshold), App Live will accumulate a TON of apps, and only the latest one is the one I want to be available for manual testing. T

he API supports setting a `custom_id` [documented here](https://www.browserstack.com/app-live/rest-api) which suggests that by setting this field in the API request, other apps with that ID are discarded. Is this true? If so, can you add an input to the `uploadDebugToBrowserstackAppLive` gradle task to set a `custom_id`?

**Comment by deepwired** [comment]
Hey,

if you set "customId" in your [ app/build.gradle](https://github.com/browserstack/espresso-browserstack/blob/gradlePluginTestBranch/app/build.gradle#L71)  file, we forward it to Browserstack as well. Does this existing implementation solve your problem?
ref: 

OR

is there a particular use-case, cause of which we need to allow customId as a param to the gradle task

**Comment by deepwired** [comment]
Closing this issue, please re-open incase there are any concerns.

**Comment by mannoeu** [comment]
> Reference in n

I have a similar issue. My team needs to upload different branches for QA to run tests. We need a custom id per task (we use the task identifier in Jira) so we don't keep 10 uploads of the same task in cache. Our flow should look like:
1. Upload the file to BrowserStack with task identification
2. QA performs the tests
2.1 If it finds something to be fixed, the developer is alerted and sends a new build that overwrites the previous one
2.2 If you don't find it, finish it.
