### ISSUE TITLE
BROWSERSTACK_LOCAL_IDENTIFIER Support

### ISSUE THREAD

**Issue by SachaTe** [browserstack/browserstack-gradle-plugin#64]
Wondering how we can set the `BROWSERSTACK_LOCAL_IDENTIFIER` as it seems to be unsupported. This would hopefully allow us integrate github actions as specified https://www.browserstack.com/docs/automate/selenium/github-actions.

**Comment by bs-ashwanipathak** [comment]
The BROWSERSTACK_LOCAL_IDENTIFIER variable will be set during BrowserStack Local binary initialisation command and then the same can be set with the system environment variable to be accessible in the test code.

**Comment by SachaTe** [comment]
Do you have an example of this ? The only way I see to set this, is to grab if from the printout, however It does not seem to be exported.

Thanks a lot for the help!

**Comment by SachaTe** [comment]
Do you have any advice of where we can fetch these sort of outputs (i.e. build id, etc.) without having to parse the output of the command ?

**Comment by rohit-y180** [comment]
you can get the details from the dashboard.
Alternatively, you can use the APIs mentioned in this documentation: https://www.browserstack.com/docs/automate/api-reference/selenium/introduction

**Comment by SachaTe** [comment]
Yes for sure, but if I am trying to automate this. What is the best way to capture the build id details ? Are they being saved, exported to a file or only printed in the console
